<?php
    return [
        'admin' => 1,
        'supervisor' => 2,
        'member' =>3,
        'paginate_user' => 5,
        'paginate_course' => 7,
        'course_start' => 1,
        'course_ready' => 0,
        'course_end' => 2,
        'date_format' => 'm/d/Y',
        'paginate_subject' => 10,
        'rows' => 5,
        'subject_ready' => 0,
        'subject_end' => 2,
        'subject_start' => 1,
        'phone' => '(+88) 111 555 666',
        'email' => 'admin@gmail.com',
        'paginate_course_public' => 6,
        'rows_subject' => 30,
        'paginate_report' => 10,
        'progress' => 100,
        'read' => 1,
        'close' => 2,
        'report' => 3,
        'paginate_history' => 10,
        'paginate_calendar' => 10,
        'count' => 1,
        'paginate_course_end' => 6
    ];
